[telethon]
# Get your own Telegram API key from https://my.telegram.org/apps.
api_id = 123456
api_hash = 0123456789abcdef0123456789abcdef
# redis_endpoint = redis-66699.x66.us-east-0-0.xx0.cloud.redislabs.com:66699
# redis_password = Youcantcatchthis&123

[userbot]
# Uncomment the things you'd want to change.
# auto or none for the sticker packs uses the default pack name and nickname
# setting a prefix locks the prefix to the one you specified. (do resetprefix to undo it via bot)
console_logger_level = INFO
# pm_permit = True
# logger_group_id = -1001234567890
# userbot_prefix = .
# default_sticker_pack = auto
# default_animated_sticker_pack = auto
# userbot_regexninja = True
# self_destruct_msg = True

[api_keys]
# api_key_heroku = Youcantcatchthis&123
# api_key_removebg = None


# Don't modify anything below this unless you know what you're doing!

# https://github.com/settings/tokens/new, to access private repos enable "repo"
# You can add multiple repo links using the format shown in inlcude key as well
# Using include and exclude both won't work. That just makes you not smart.
[plugins]
enabled = True
root = userbot/plugins
# user = notkandnub
# token = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
# repos = user/repo, www.github.com/user1/repo1/
# include = misc
#     www
# exclude = www
#   misc

# Currently useless. Skip it.
[proxy]
enabled = False
hostname = 11.22.33.44
port = 1080
username = <your_username>
password = <your_password>
BOTLOG = True

# Set this to True if you want the error logs to be stored in
# the userbot log, rather than spamming other chats with it.
# Note that this requires a valid BOTLOG_CHATID to be set.
LOGSPAMMER = True

# If you need Verbosity on the Logging
CONSOLE_LOGGER_VERBOSE = False

# PM Auto-Ban Feature Switch
PM_AUTO_BAN = False

# Custom Default name for .alive
ALIVE_NAME = None

# Your Database URL
# Example: 'postgres://userbot:userbot@localhost:5432/userbot'
DATABASE_URL = ""

# YouTube Data API Key for .yt command
# Get from https://console.cloud.google.com
YOUTUBE_API_KEY = ""

# Country and Time Zone setup for
# .time and .date modules
COUNTRY = ""
TZ_NUMBER = # this is an integer, please don't use quotes.

# Google Drive Credentials
# for .gdrive module.
# Get from https://console.cloud.google.com
G_DRIVE_CLIENT_ID = ""
G_DRIVE_CLIENT_SECRET = ""
G_DRIVE_AUTH_TOKEN_DATA = ""
TEMP_DOWNLOAD_DIRECTORY = ""

# You have to have your own unique two values for API_KEY and API_SECRET
# Obtain yours from https://www.last.fm/api/account/create for Last.fm
LASTFM_API = None
LASTFM_SECRET = None
LASTFM_USERNAME = None # Your last.fm username
LASTFM_PASSWORD = "Your last.fm password"

# Bot will add before song name. For last.fm module.
# Example: GitHub: MacTavishAO : Skillet - Feel Invincible
BIO_PREFIX = ""

# default bio message
DEFAULT_BIO = ""

# Report or kick some known spammer bots after
# they joins
ANTI_SPAMBOT = False
ANTI_SPAMBOT_SHOUT = False

GOOGLE_CHROME_BIN = ""

# OCR Space API Key for .ocr command
# Get from https://ocr.space/ocrapi
OCR_SPACE_API_KEY = ""

# remove.bg API Key for .rbg command
# Get from https://www.remove.bg/api
REM_BG_API_KEY = ""

# OpenWeather Map API Key for .weather command
# Get from https://openweathermap.org/
OPEN_WEATHER_MAP_APPID = ""
WEATHER_DEFCITY = ""

# Location of ChromeDriver for .carbon module
# Example for Linux Machines : "/usr/bin/chromedriver"
CHROME_DRIVER = ""
